# ML-04 — Search Intelligence Data Contract

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*


For this project, I will analyze one webpage at a time using SEO and analytics data.

The primary time window for development is **March 2026 (2026-03)** because it is a mid-panel month and avoids using the final outcome month.

The final month (June 2026) will not be used for feature engineering because it represents the natural outcome period.

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*
Fields
Features
search_clicks
search_impressions
ctr
average_position
engagement_rate
These variables are available before making the refresh decision.

Label (Target)
Refresh Priority Score

This score represents how important it is to refresh a webpage.

Context
content_id
client_hash_id
month
These fields identify the webpage and time period.

Excluded Fields
Future performance metrics
Any information collected after the refresh decision
These are excluded to avoid data leakage.

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [1]:
import pandas as pd
from datasets import load_dataset
from google.colab import userdata
HF_TOKEN = userdata.get("HF_TOKEN")
print(HF_TOKEN[:10])

hf_zUlBMZt

In [2]:
from datasets import load_dataset

dataset = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance", # Corrected dataset name
    token=HF_TOKEN
)

README.md:   0%|          | 0.00/3.04k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/39 [00:00<?, ?it/s]

In [3]:
dataset

DatasetDict({
    train: Dataset({
        features: ['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events'],
        num_rows: 78835655
    })
})

In [4]:
df = dataset["train"].select(range(10000)).to_pandas()

print(df.shape)
df.head()

(10000, 30)

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
0,2025-01-27,client_9958f0a7ae1df715,content_3b70a18ea133b2bb,True,True,True,False,30,0,115.0,...,0,0,0,0,0,0,0,0,0,0
1,2025-01-27,client_9958f0a7ae1df715,content_fe8e8155ce1d47a2,True,True,True,False,5,0,358.0,...,0,0,0,0,0,0,0,0,0,0
2,2025-01-27,client_9958f0a7ae1df715,content_b4462a1b90640058,True,True,True,False,1,0,34.0,...,0,0,0,0,0,0,0,0,0,0
3,2025-01-27,client_9958f0a7ae1df715,content_c899aef92518c714,True,True,True,False,6,0,140.0,...,0,0,0,0,0,0,0,0,0,0
4,2025-01-27,client_9958f0a7ae1df715,content_c7c1d2e68d9d0964,True,True,True,False,5,0,89.0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df.columns.tolist()

['report_date',
 'client_hash_id',
 'content_hash_id',
 'client_has_gsc',
 'client_has_ga4',
 'gsc_data_available',
 'ga4_data_available',
 'gsc_impressions',
 'gsc_clicks',
 'gsc_sum_position',
 'gsc_avg_position',
 'ga4_pageviews',
 'ga4_sessions',
 'ga4_users',
 'ga4_engaged_sessions',
 'ga4_total_engagement_sec',
 'sessions_organic',
 'sessions_direct',
 'sessions_referral',
 'sessions_social',
 'sessions_paid',
 'sessions_ai',
 'ai_chatgpt',
 'ai_perplexity',
 'ai_gemini',
 'ai_copilot',
 'ai_claude',
 'ai_meta',
 'ai_other',
 'scroll_events']

In [9]:
print(df[['report_date','client_hash_id','content_hash_id']].head())
print("Rows:", len(df))
print("Start Date:", df['report_date'].min())
print("End Date:", df['report_date'].max())
available = df[
    (df['gsc_data_available'] == True) &
    (df['ga4_data_available'] == True)
]

print("Available Rows:", len(available))

  report_date           client_hash_id           content_hash_id
0  2025-01-27  client_9958f0a7ae1df715  content_3b70a18ea133b2bb
1  2025-01-27  client_9958f0a7ae1df715  content_fe8e8155ce1d47a2
2  2025-01-27  client_9958f0a7ae1df715  content_b4462a1b90640058
3  2025-01-27  client_9958f0a7ae1df715  content_c899aef92518c714
4  2025-01-27  client_9958f0a7ae1df715  content_c7c1d2e68d9d0964
Rows: 10000
Start Date: 2025-01-27
End Date: 2025-02-14
Available Rows: 0

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

This dataset does not include every possible SEO factor.

The sample loaded into memory is only a small subset of the complete warehouse.

External ranking factors such as backlinks, competitors, and Google algorithm updates are not included.

The final month should not be used for feature engineering because it represents the outcome period and may introduce data leakage.

In [10]:
# Five Feature Frame

feature_df = df[[
    'gsc_impressions',
    'gsc_clicks',
    'gsc_avg_position',
    'ga4_pageviews',
    'ga4_sessions'
]]

feature_df.head()

   gsc_impressions  gsc_clicks  gsc_avg_position  ga4_pageviews  ga4_sessions
0               30           0          3.833333              0             0
1                5           0         71.600000              0             0
2                1           0         34.000000              0             0
3                6           0         23.333333              0             0
4                5           0         17.800000              0             0

Five Features Used

1. gsc_impressions
Available because impressions are already known when making the prediction.

2. gsc_clicks
Available because historical click data exists before prediction.

3. gsc_avg_position
Available because average search position is recorded before the prediction date.

4. ga4_pageviews
Available because pageviews are historical analytics data.

5. ga4_sessions
Available because session counts are available before making any prediction.

In [11]:
# Deliberate Leakage Example

feature_df["leak_feature"] = df["sessions_organic"]

feature_df.head()

/tmp/ipykernel_675/3418456368.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  feature_df["leak_feature"] = df["sessions_organic"]

,gsc_impressions,gsc_clicks,gsc_avg_position,ga4_pageviews,ga4_sessions,leak_feature
0,30,0,3.833333,0,0,0
1,5,0,71.600000,0,0,0
2,1,0,34.000000,0,0,0
3,6,0,23.333333,0,0,0
4,5,0,17.800000,0,0,0

In [12]:
# Remove leakage

feature_df = feature_df.drop(columns=["leak_feature"])

feature_df.head()

   gsc_impressions  gsc_clicks  gsc_avg_position  ga4_pageviews  ga4_sessions
0               30           0          3.833333              0             0
1                5           0         71.600000              0             0
2                1           0         34.000000              0             0
3                6           0         23.333333              0             0
4                5           0         17.800000              0             0

Leakage Experiment

I intentionally added the target variable (sessions_organic) as an input feature.

This would produce unrealistically high model performance because the model already knows the answer.

This feature must be removed before model training.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.