<a href="https://colab.research.google.com/github/Abhaykr45/flyrank-ml-internship/blob/main/work/notebooks/w04_baseline_score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-07 — Baseline Action Score and Top-20 Review

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My rule and its reason codes

*Write the rule in plain words first. Then the reason codes it can output.*
## My Baseline Rule

My baseline rule identifies content that is a good candidate for refresh.

The rule prioritizes pages that have:
- High search impressions (strong visibility)
- Low click-through rate (CTR), indicating users are not clicking despite seeing the page
- Low average position, suggesting ranking improvements could increase traffic

The purpose of this rule is to create a ranked list of content that should be reviewed for optimization before applying a machine learning model.

### Reason Codes

- HIGH_IMPRESSIONS_LOW_CTR
- LOW_RANKING_HIGH_IMPRESSIONS
- REFRESH_RECOMMENDED

## 2. Build the ranked queue (writes the CSV)

*Code the score, rank everything, write work/outputs/baseline_action_score.csv.*

In [14]:
!git clone https://github.com/Abhaykr45/flyrank-ml-internship.git

fatal: destination path 'flyrank-ml-internship' already exists and is not an empty directory.

In [15]:
import pandas as pd

df = pd.read_csv("flyrank-ml-internship/data/raw/content_refresh_anonymized.csv")

In [16]:
print(df.columns)

Index(['content_id', 'client_id', 'search_volume', 'competition',
       'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count',
       'char_count', 'provider_used', 'model_used', 'impressions_90d',
       'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d',
       'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d',
       'days_with_impressions', 'days_with_sessions', 'impressions_last_30d',
       'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d',
       'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier',
       'age_tier_order', 'days_since_last_update', 'freshness_tier',
       'word_count_tier', 'char_count_tier', 'ctr', 'avg_position',
       'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier',
       'position_tier', 'trend_direction', 'trend_pct'],
      dtype='object')

In [17]:
print(df.columns.tolist())

['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

In [18]:
# Baseline Score

df["score"] = (
    (df["impressions_90d"] * 0.5)
    + ((100 - df["ctr"]) * 0.3)
    + (df["avg_position"] * 0.2)
)

df[["impressions_90d", "ctr", "avg_position", "score"]].head()

   impressions_90d   ctr  avg_position     score
0             3803  0.76          10.6  1933.392
1            15320  0.05          20.3  7694.045
2            12581  0.09          36.5  6327.773
3            11751  0.49           6.2  5906.593
4            19140  0.13          44.0  9608.761

In [19]:
# Reason Code

df["reason_code"] = "REFRESH_RECOMMENDED"

# Action Label

df["action"] = "Refresh Content"

df[["score", "reason_code", "action"]].head()

      score          reason_code           action
0  1933.392  REFRESH_RECOMMENDED  Refresh Content
1  7694.045  REFRESH_RECOMMENDED  Refresh Content
2  6327.773  REFRESH_RECOMMENDED  Refresh Content
3  5906.593  REFRESH_RECOMMENDED  Refresh Content
4  9608.761  REFRESH_RECOMMENDED  Refresh Content

In [20]:
# Rank by score

df = df.sort_values("score", ascending=False)

df.head(10)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct,score,reason_code,action
6653,content_5fe46e04994d,client_4e07408562,1900.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,...,4.23,26.90,0.38,excellent,page_1,down,-44.8,258888.298,REFRESH_RECOMMENDED,Refresh Content
17812,content_aaef01a50def,client_19581e27de,4400.0,0.05,LOW,0.11,keyword article,informational,NaN,NaN,...,2.42,4.77,0.00,excellent,page_1,stable,-4.0,258585.505,REFRESH_RECOMMENDED,Refresh Content
26844,content_8c19996aa890,client_4e07408562,70.0,0.01,LOW,0.00,keyword article,informational,2895.0,19343.0,...,11.73,16.03,0.00,excellent,top_3,down,-44.5,254656.455,REFRESH_RECOMMENDED,Refresh Content
19636,content_2cb567c3c89b,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,6183.0,39587.0,...,5.82,5.64,1.21,excellent,page_3_5,up,23.1,248897.910,REFRESH_RECOMMENDED,Refresh Content
21819,content_4c36c775b818,client_4e07408562,40.0,0.00,LOW,0.00,keyword article,informational,3097.0,20514.0,...,11.31,18.07,0.00,excellent,top_3,down,-33.2,231581.837,REFRESH_RECOMMENDED,Refresh Content
29400,content_2dba2b1f9536,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,7676.0,48015.0,...,2.73,7.77,0.43,excellent,page_3_5,stable,1.4,221752.517,REFRESH_RECOMMENDED,Refresh Content
29879,content_1a9e894be2e2,client_19581e27de,70.0,0.07,LOW,0.10,keyword article,transactional,NaN,NaN,...,2.37,4.97,0.00,excellent,page_1,down,-27.0,208120.731,REFRESH_RECOMMENDED,Refresh Content
13537,content_2c2606c5d176,client_19581e27de,590.0,0.18,LOW,0.31,keyword article,commercial,NaN,NaN,...,1.30,3.28,0.00,excellent,page_1,down,-36.5,173730.181,REFRESH_RECOMMENDED,Refresh Content
18870,content_db5989a78dd3,client_4e07408562,110.0,0.00,LOW,0.00,keyword article,commercial,2682.0,17806.0,...,2.32,3.72,0.00,excellent,page_1,up,556.2,172586.517,REFRESH_RECOMMENDED,Refresh Content
14090,content_44e481c8f55b,client_19581e27de,20.0,0.26,LOW,0.43,keyword article,transactional,3040.0,21293.0,...,0.76,2.78,0.00,excellent,top_3,stable,-11.6,156377.085,REFRESH_RECOMMENDED,Refresh Content

In [21]:
import os

os.makedirs("work/outputs", exist_ok=True)

df.to_csv(
    "work/outputs/baseline_action_score.csv",
    index=False
)

print("CSV created successfully!")

CSV created successfully!

In [22]:
df.head(20)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct,score,reason_code,action
6653,content_5fe46e04994d,client_4e07408562,1900.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,...,4.23,26.90,0.38,excellent,page_1,down,-44.8,258888.298,REFRESH_RECOMMENDED,Refresh Content
17812,content_aaef01a50def,client_19581e27de,4400.0,0.05,LOW,0.11,keyword article,informational,NaN,NaN,...,2.42,4.77,0.00,excellent,page_1,stable,-4.0,258585.505,REFRESH_RECOMMENDED,Refresh Content
26844,content_8c19996aa890,client_4e07408562,70.0,0.01,LOW,0.00,keyword article,informational,2895.0,19343.0,...,11.73,16.03,0.00,excellent,top_3,down,-44.5,254656.455,REFRESH_RECOMMENDED,Refresh Content
19636,content_2cb567c3c89b,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,6183.0,39587.0,...,5.82,5.64,1.21,excellent,page_3_5,up,23.1,248897.910,REFRESH_RECOMMENDED,Refresh Content
21819,content_4c36c775b818,client_4e07408562,40.0,0.00,LOW,0.00,keyword article,informational,3097.0,20514.0,...,11.31,18.07,0.00,excellent,top_3,down,-33.2,231581.837,REFRESH_RECOMMENDED,Refresh Content
29400,content_2dba2b1f9536,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,7676.0,48015.0,...,2.73,7.77,0.43,excellent,page_3_5,stable,1.4,221752.517,REFRESH_RECOMMENDED,Refresh Content
29879,content_1a9e894be2e2,client_19581e27de,70.0,0.07,LOW,0.10,keyword article,transactional,NaN,NaN,...,2.37,4.97,0.00,excellent,page_1,down,-27.0,208120.731,REFRESH_RECOMMENDED,Refresh Content
13537,content_2c2606c5d176,client_19581e27de,590.0,0.18,LOW,0.31,keyword article,commercial,NaN,NaN,...,1.30,3.28,0.00,excellent,page_1,down,-36.5,173730.181,REFRESH_RECOMMENDED,Refresh Content
18870,content_db5989a78dd3,client_4e07408562,110.0,0.00,LOW,0.00,keyword article,commercial,2682.0,17806.0,...,2.32,3.72,0.00,excellent,page_1,up,556.2,172586.517,REFRESH_RECOMMENDED,Refresh Content
14090,content_44e481c8f55b,client_19581e27de,20.0,0.26,LOW,0.43,keyword article,transactional,3040.0,21293.0,...,0.76,2.78,0.00,excellent,top_3,stable,-11.6,156377.085,REFRESH_RECOMMENDED,Refresh Content
26531,content_cb112fce36be,client_19581e27de,70.0,0.65,MEDIUM,0.34,keyword article,transactional,2761.0,18472.0,...,2.08,2.95,0.00,excellent,page_1,down,-41.8,154986.072,REFRESH_RECOMMENDED,Refresh Content
21565,content_9532f197bbc8,client_4e07408562,10.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,...,8.01,28.75,0.00,excellent,top_3,down,-37.3,154626.139,REFRESH_RECOMMENDED,Refresh Content
3394,content_36ff89c8214e,client_19581e27de,0.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,...,1.68,4.48,0.00,excellent,page_1,stable,0.5,147579.945,REFRESH_RECOMMENDED,Refresh Content
16811,content_8e7ba84a972b,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3731.0,23829.0,...,1.19,37.88,0.00,excellent,page_1,stable,-18.1,144243.684,REFRESH_RECOMMENDED,Refresh Content
26798,content_b28d1efd668f,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,transactional,6901.0,44938.0,...,3.83,6.57,0.96,excellent,page_3_5,stable,-17.2,143339.222,REFRESH_RECOMMENDED,Refresh Content
14234,content_89e84d699e9e,client_349c41201b,50.0,0.05,LOW,0.08,keyword article,informational,3480.0,22147.0,...,0.70,1.08,0.00,excellent,page_1,stable,-14.8,137643.693,REFRESH_RECOMMENDED,Refresh Content
7678,content_8451fc6f034d,client_d029fa3a95,10.0,1.00,HIGH,14.11,keyword article,informational,3528.0,24856.0,...,2.02,2.26,2.02,excellent,top_3,up,73.1,136102.451,REFRESH_RECOMMENDED,Refresh Content
15250,content_aa4baf490b43,client_349c41201b,30.0,0.26,LOW,0.02,keyword article,commercial,2715.0,17584.0,...,1.49,1.90,0.00,excellent,page_1,stable,-13.3,128176.030,REFRESH_RECOMMENDED,Refresh Content
27478,content_008fb02c46cb,client_349c41201b,10.0,0.86,HIGH,0.00,keyword article,commercial,3338.0,21685.0,...,1.14,1.47,0.00,excellent,page_1,down,-21.3,118432.302,REFRESH_RECOMMENDED,Refresh Content
23767,content_813e88069237,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,commercial,4610.0,30146.0,...,1.37,10.37,0.52,excellent,page_3_5,down,-33.8,116815.722,REFRESH_RECOMMENDED,Refresh Content

## 3. Top-20 review

*For each of the top 20: action, reason code, confidence note, and what would make it wrong.*

## Top-20 Review

The baseline ranking prioritizes pages with high impressions, low CTR, and lower search positions.

For each of the top-ranked pages:

- **Action:** Refresh Content
- **Reason Code:** REFRESH_RECOMMENDED
- **Confidence:** Medium
- **What would make it wrong?**
  - The page was recently updated.
  - Traffic is seasonal.
  - CTR is low because of search intent rather than content quality.
  - Ranking changes are temporary.

## 4. Weak picks + leakage check

*Which picks look wrong and why? Confirm no product flags or future windows leaked in.*
## Weak Picks + Leakage Check

### Weak Picks

Some pages may receive high scores even though they do not require updates. Seasonal trends, recent content updates, or temporary ranking fluctuations may affect the ranking.

### Leakage Check

This baseline uses only current available information such as impressions, CTR, and average position. It does not use future performance, labels, or outcome variables. Therefore, no data leakage is present.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.